name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
  pull_request:
    paths-ignore:
      - "docs/**"

jobs:
  linux:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9"]

    env:
      OS: "linux"
      PYTHON: ${{ matrix.python-version }}

    steps:
      - name: Checkout our source
        uses: actions/checkout@v2
        with:
          path: conda-libmamba-solver
          fetch-depth: 0

      - name: Checkout conda
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: conda/conda
          ref: libmamba-migration
          path: conda

      - name: Merge repositories
        run: mv conda-libmamba-solver conda/

      - name: Python ${{ matrix.python-version }}
        working-directory: conda
        run: >
          docker run
          --rm -v ${PWD}:/opt/conda-src
          -e TEST_SPLITS
          -e TEST_GROUP
          -e CONDA_SOLVER_LOGIC
          ghcr.io/conda/conda-ci:poc-libsolv-linux-python${{ matrix.python-version }}-mamba
          bash -c "/opt/conda/bin/python -m pip install /opt/conda-src/conda-libmamba-solver --no-deps -vvv &&
                   source /opt/conda-src/dev/linux/bashrc.sh &&
                   /opt/conda/bin/python -m pytest /opt/conda-src/conda-libmamba-solver/ -vv"
