name: Upstream

on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
  pull_request:
    paths-ignore:
      - "docs/**"

jobs:
  linux:
    name: Linux, Python ${{ matrix.python-version }}, ${{ matrix.conda-solver-logic }}, ${{ matrix.test-type }}, group ${{ matrix.test-group }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
        conda-solver-logic: ["libmamba"]
        test-group: ["1", "2", "3"]
        test-splits: ["3"]
        test-type: ["integration"]
        include:
          - python-version: "3.7"
            test-type: "experimental-resolver"
            test-group: "1"
            conda-solver-logic: "libmamba"
          - python-version: "3.8"
            test-type: "experimental-resolver"
            test-group: "1"
            conda-solver-logic: "libmamba"
          - python-version: "3.9"
            test-type: "experimental-resolver"
            test-group: "1"
            conda-solver-logic: "libmamba"

    env:
      OS: "linux"
      PYTHON: ${{ matrix.python-version }}
      TEST_SPLITS: ${{ matrix.test-splits }}
      TEST_GROUP: ${{ matrix.test-group }}
      CONDA_SOLVER_LOGIC: ${{ matrix.conda-solver-logic }}

    steps:
      - name: Checkout our source
        uses: actions/checkout@v2
        with:
          path: conda-libmamba-solver
          fetch-depth: 0

      - name: Checkout conda
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: conda/conda
          ref: poc-libsolv
          path: conda

      - name: Python ${{ matrix.python-version }} ${{ matrix.test-type }} tests, group ${{ matrix.test-group }}
        working-directory: conda
        run: >
          docker run
          --rm
          -v ${GITHUB_WORKSPACE}/conda:/opt/conda-src
          -v ${GITHUB_WORKSPACE}/conda-libmamba-solver:/opt/conda-libmamba-solver-src
          -e TEST_SPLITS
          -e TEST_GROUP
          -e CONDA_SOLVER_LOGIC
          ghcr.io/conda/conda-ci:poc-libsolv-linux-python${{ matrix.python-version }}-mamba
          bash -c "/opt/conda/bin/python -m pip install /opt/conda-libmamba-solver-src --no-deps -vvv &&
                   source /opt/conda-src/dev/linux/${{ matrix.test-type }}.sh"

  macos:
    name: MacOS, Python ${{ matrix.python-version }}, ${{ matrix.conda-solver-logic }}, ${{ matrix.test-type }}, group ${{ matrix.test-group }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
        conda-solver-logic: ["libmamba"]
        test-group: ["1", "2", "3"]
        test-splits: ["3"]
        test-type: ["integration"]
        include:
          - python-version: "3.7"
            test-type: "experimental-resolver"
            test-group: "1"
            conda-solver-logic: "libmamba"
          - python-version: "3.8"
            test-type: "experimental-resolver"
            test-group: "1"
            conda-solver-logic: "libmamba"
          - python-version: "3.9"
            test-type: "experimental-resolver"
            test-group: "1"
            conda-solver-logic: "libmamba"

    env:
      OS: "macos"
      PYTHON: ${{ matrix.python-version }}
      TEST_SPLITS: ${{ matrix.test-splits }}
      TEST_GROUP: ${{ matrix.test-group }}
      CONDA_SOLVER_LOGIC: ${{ matrix.conda-solver-logic }}

    steps:
      - name: Checkout our source
        uses: actions/checkout@v2
        with:
          path: conda-libmamba-solver
          fetch-depth: 0

      - name: Checkout conda
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: conda/conda
          ref: poc-libsolv
          path: conda

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: conda-test-env
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!

      - name: Setup environment
        shell: bash -l {0}
        working-directory: conda
        run: |
          set -euxo pipefail
          # restoring the default for changeps1 to have parity with dev
          conda config --set changeps1 true
          # make sure the caching works correctly
          conda config --set use_only_tar_bz2 true
          # install all test requirements
          conda install --yes --file tests/requirements.txt python=${{ matrix.python-version }}
          conda update openssl ca-certificates certifi
          conda info
          mamba --version

      - name: Install conda-libmamba-solver
        shell: bash -l {0}
        working-directory: conda-libmamba-solver
        run: |
          python -m pip install . -vv --no-deps

      - name: Python ${{ matrix.python-version }} ${{ matrix.test-type }} tests, group ${{ matrix.test-group }}
        shell: bash -l {0}
        working-directory: conda
        run: |
          ./dev/macos/${{ matrix.test-type }}.sh

  windows:
    name: Windows, Python ${{ matrix.python-version }}, ${{ matrix.conda-solver-logic }}, ${{ matrix.test-type }}, group ${{ matrix.test-group }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
        conda-solver-logic: ["libmamba"]
        test-group: ["1", "2", "3"]
        test-splits: ["3"]
        test-type: ["integration"]
        include:
          - python-version: "3.7"
            test-type: "experimental-resolver"
            test-group: "1"
            conda-solver-logic: "libmamba"
          - python-version: "3.8"
            test-type: "experimental-resolver"
            test-group: "1"
            conda-solver-logic: "libmamba"
          - python-version: "3.9"
            test-type: "experimental-resolver"
            test-group: "1"
            conda-solver-logic: "libmamba"

    env:
      OS: "windows"
      PYTHON: ${{ matrix.python-version }}
      TEST_SPLITS: ${{ matrix.test-splits }}
      TEST_GROUP: ${{ matrix.test-group }}
      CONDA_SOLVER_LOGIC: ${{ matrix.conda-solver-logic }}

    steps:
      - name: Checkout our source
        uses: actions/checkout@v2
        with:
          path: conda-libmamba-solver
          fetch-depth: 0

      - name: Checkout conda
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: conda/conda
          ref: poc-libsolv
          path: conda

      - name: Set temp dirs correctly
        # https://github.com/actions/virtual-environments/issues/712
        run: |
          echo "TMPDIR=$env:USERPROFILE\AppData\Local\Temp" >> $env:GITHUB_ENV
          echo "TEMP=$env:USERPROFILE\AppData\Local\Temp" >> $env:GITHUB_ENV
          echo "TMP=$env:USERPROFILE\AppData\Local\Temp" >> $env:GITHUB_ENV

      - name: Setup environment
        shell: cmd
        working-directory: conda
        run: |
          call .\dev\windows\setup.bat
          if errorlevel 1 exit 1
          call .\dev-init.bat
          if errorlevel 1 exit 1
          mamba --version
          conda info -a
          if errorlevel 1 exit 1

      - name: Install conda-libmamba-solver
        shell: cmd
        working-directory: conda
        run: |
          call .\dev-init.bat
          if errorlevel 1 exit 1
          python -m pip install --no-deps -vv "%GITHUB_WORKSPACE%\conda-libmamba-solver"
          if errorlevel 1 exit 1

      - name: Python ${{ matrix.python-version }}, ${{ matrix.test-type }} tests, group ${{ matrix.test-group }}
        shell: cmd
        working-directory: conda
        run: |
          call .\dev\windows\${{ matrix.test-type }}.bat
